### ISSUE TITLE
Add a test to ensure that primitive functions can be lazily evaluated

### ISSUE THREAD

**Issue by dhess** [hackworthltd/primer#1118]
We recently re-opened discussions on https://github.com/hackworthltd/primer/issues/272, and decided that the current implementation of primitive functions is sufficient. However, we do want to ensure that a clever primitive function can lazily evaluate its arguments; e.g., it should be possible to write a primitive function like `primitiveConst True ?` and have it return `True` without getting stuck on the hole.

Let's add a test(s) to the test suite to verify these semantics.

**Comment by brprice** [comment]
Ideas for the lazy-primitive test:
- const (lazy): `const 0 (let x = x in x) ~> 0` (in 1 step); `const 0 ? ~> 0`
- different arity branches: `foo : Bool -> Bool -> Bool` with "equations" `foo True = id; foo False True = False; foo False False = True` and check `foo True` reduces but `foo False` does not

But also note (and test) that because we reduce children left-to-right, matching on a later child could still diverge: a flipped `const` would be fine as it does not care about the shape of its child, but defining `bar x True = 0; bar x False = ...` and evaluating `bar (let x = x in x) True ~> 0` will work, but `bar (let x = x in x) (not False)` will diverge as we reduce the first child before the second.

NB: I'm not claiming that the above is the best possible / our goal, but I think it should capture the current behaviour

**Comment by dhess** [comment]
Bumping this to high priority. I would like to wrap up the Primer 1.0 def ASAP, and this is part of it.

**Comment by brprice** [comment]
FTR, this is closed by #1151, which only adds the "lazy const" test. It does not add any other tests (notably "different arity branches"), for reasons explained in its commit message.
