### ISSUE TITLE
Eval: partial application of primitive functions

### ISSUE THREAD

**Issue by georgefst** [hackworthltd/primer#272]
We have discussed various approaches for dealing with partially-applied primitives in eval mode:

1. Cannot be reduced until fully applied and all args are fully evaluated (this is what's currently implemented)
    - We need to consider holes here. Perhaps we should aim for the property "can be reduced iff there are no holes or redexes in arguments".
    - We _may_ want to consider allowing for primitives to be lazy in one or more arguments. Though none of us has yet come up with an example of a useful lazy primitive.
3. Cannot be reduced until fully applied
4. Reduce to a special form
5. Wrap them in a lambda

There is more detail in the [2021-12-08 Primer definition meeting](https://docs.craft.do/editor/d/8b43f204-aeeb-b8ce-45cc-73a653745299/2ECD6193-27AD-4431-8A64-B317B2DD863C) notes.

My personal preference is very strongly towards some variation of 1 or 2. It was worth exploring the other ideas, but we failed to come up with anything elegant enough to justify the complexity.

Our major concern with 1 is that it effectively makes primitive functions call-by-value, when Primer aims to be flexible about evaluation order.

On the other hand, 2 would involve some very large single steps in the evaluator. But we might end up with more of these anyway, outside the context of primitives, such as an "evaluate this whole tree in one step" shortcut.

**Comment by brprice** [comment]
The current status is that option 1 above has been implemented in the sense that
- a primitive (from Eval's viewpoint) is essentially a haskell-function `[Expr] -> Maybe Expr` that gets given a list of arguments and returns the reduct of that primitive applied to those arguments (or `Nothing` if not a redex)
- all the implemented primitves happen to pattern-match on the given argument list, with one success branch ensuring it is the correct length and all args are canonical inhabitants of the expected type (i.e. mostly primitive constructors for `Char` and `Int`, but occasionally a peano natural: one of `Z`, `S Z`, `S (S Z)` etc)

Note that this implementation is flexible and could be persuaded to do some odd reductions, but likely a different design would be preferable if we change our mind here.

--- 

I think this ticket is less about "what (eval) result should we give to `primitiveAddtion 3` from a theory standpoint" as it is about "how should this be represented to a student". Having said that, option 4 could be an argument for representing applications of primitive operations as always-fully-applied (like we do for ADT constructors).

---

I think I am happy with the status quo, but maybe simply because I have not got a good idea of what else we could sensibly do.

Perhaps having some explicit examples may help (here I use `+`, `1` etc for primitive integers)
- unapplied, top level : `+`
- partial, top level   : `1 +`
- unapplied, in map    : `map (+) [0..4]`
- partial, in map      : `map (1 +) [0..4]`

**Comment by dhess** [comment]
It's an interesting idea to treat primitive functions like we now treat value constructors, but I expect that primitive functions will be too frequently passed around as function arguments (e.g., to `map`) to get away with this. It would be very un-ergonomic.

Let's keep this idea in mind as we do initial testing, but not implement it yet.

**Comment by brprice** [comment]
> IMO. Then again, that assumes that beginners would go poking around the Prelude definitions, which seems unlikely, so maybe it would suffice?

Presumably they would see the unfolding in interactive evaluations though

**Comment by dhess** [comment]
Yes, good point.

**Comment by georgefst** [comment]
> It's an interesting idea to treat primitive functions like we now treat value constructors

Yes, I'm also intrigued by this. It might make it a lot easier to explain why a primitive application can not be evaluated. But we might have to wait until we actually have an interactive eval mode before we can really weigh this up.

**Comment by dhess** [comment]
In our 2023-08-16 meet-up, we discussed saturated primitives in more detail. The main drawback to this approach is that saturated primitive functions, like saturated value constructors, would need to be wrapped in a lambda to be used HOF-style, which we expect to be a fairly common usage pattern. 

Primitive functions are already different to student-defined functions because they can't be inspected or step-evaluated, and making this change would make them different than student-defined functions in yet another way, which seems a bit pointless. When also accounting for the worse ergonomics due to requiring the lambda-wrapping, we grudgingly felt it would be too difficult to justify this change in semantics.

I believe this means we can now close this issue. We do want to ensure that the current implementation of primitive functions can lazily evaluate their arguments given a sufficiently clever primitive function implementation, so we'll add at least one new test to the test suite to confirm that this is the case. That is tracked in https://github.com/hackworthltd/primer/issues/1118
